server:
  port: 18085
  tongweb:
    license:
      type: file
      path: classpath:license.dat
spring:
  application:
    name: provider-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: dev
#        group: my-group