server:
  port: 28090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gateway-admin
#  boot:
#    admin:
#      server:
#        enabled: true
#      instance-auth:
#        default-user-name: admin
#        default-password: 123456